version: '3.1'

## 自定义网络
networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:
  ### nexus ################################################
  nexus:
    container_name: nexus-${NEXUS_VERSION}
    build:
      context: ./nexus
      args:
        - NEXUS_VERSION=${NEXUS_VERSION}
    restart: always
    ports:
      - ${NEXUS_PORT}:8081
    environment:
      - TZ=${TIME_ZONE}
    volumes:
      - ${VOLUMES_PATH}/nexus:/nexus

  ### MySQL ################################################
  mysql:
    container_name: mysql-${MYSQL_VERSION}
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${TIME_ZONE}
    volumes:
      - ${VOLUMES_PATH}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  ### redis ##################################
  redis:
    build:
      context: ./redis
      args:
        - REDIS_VERSION=${REDIS_VERSION}
    container_name: redis-${REDIS_VERSION}
    volumes:
      - ${VOLUMES_PATH}/redis:/data
      - ./redis/redis-server.log:/var/log/redis/redis-server.log
    environment:
      - TZ=${TIME_ZONE}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  ### registry ##############################################
  registry:
    container_name: registry-${REGISTRY_VERSION}
    build:
      context: ./registry
      args:
        - REGISTRY_VERSION=${REGISTRY_VERSION}
    volumes:
      - ${VOLUMES_PATH}/registry:/var/lib/registry
    environment:
      - TZ=${TIME_ZONE}
    ports:
      - "${REGISTRY_PORT}:5000"

  ### consul ##################################
  consul:
    build:
      context: ./consul
      args:
        - CONSUL_VERSION=${CONSUL_VERSION}
    container_name: consul-${CONSUL_VERSION}
    volumes:
      - ${VOLUMES_PATH}/consul:/consul/data
    environment:
      - TZ=${TIME_ZONE}
    ports:
      - "8300-8302:8300-8302"
      - "8500:8500"
      - "8600:8600"
    networks:
      - backend
  ### ElasticSearch ########################################
  elasticsearch:
    container_name: elasticsearch-${ELASTICSEARCH_VERSION}
    build:
      context: ./elasticsearch
      args:
        - ELASTICSEARCH_VERSION=${ELASTICSEARCH_VERSION}
    environment:
      - cluster.name=${ELASTICSEARCH_CLUSTER_NAME}
      - node.name=${ELASTICSEARCH_NODE_NAME}
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.initial_master_nodes=${ELASTICSEARCH_NODE_NAME}
      - TZ=${TIME_ZONE}
    volumes:
      - ${VOLUMES_PATH}/elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ELASTICSEARCH_HOST_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_HOST_TRANSPORT_PORT}:9300"
    networks:
      - frontend
      - backend
  ### Logstash ##############################################
  logstash:
    container_name: logstash-${LOGSTASH_VERSION}
    build:
      context: ./logstash
      args:
        - LOGSTASH_VERSION=${LOGSTASH_VERSION}
    volumes:
      - './logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml'
      - './logstash/pipeline:/usr/share/logstash/pipeline'
    ports:
      - '5001:5001'
    environment:
      LS_JAVA_OPTS: '-Xmx1g -Xms1g'
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - elasticsearch
  ### Kibana ##############################################
  kibana:
    container_name: kibana-${KIBANA_VERSION}
    build:
      context: ./kibana
      args:
        - KIBANA_VERSION=${KIBANA_VERSION}
    volumes:
      - './kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml'
    ports:
      - "${KIBANA_HTTP_PORT}:5601"
    environment:
      - TZ=${TIME_ZONE}
    depends_on:
      - elasticsearch
    networks:
      - backend
    ### EsHead ##############################################
    eshead:
      container_name: eshead-${ESHEAD_VERSION}
      build:
        context: ./eshead
        args:
          - ESHEAD_VERSION=${ESHEAD_VERSION}
      ports:
        - "${ESHEAD_HTTP_PORT}:9100"
      environment:
        - TZ=${TIME_ZONE}
      depends_on:
        - elasticsearch
      networks:
        - backend

  ### MongoDB ##############################################
  mongo:
    build: ./mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ${VOLUMES_PATH}/mongo:/data/db
      - ${VOLUMES_PATH}/mongo_config:/data/configdb
    networks:
      - backend

  ### Zipkin ##############################################
  zipkin:
    build: ./zipkin
    container_name: zipkin
    ports:
      - "${ZIPKIN_PORT}:9411"
    environment:
      - STORAGE_TYPE=${ZIPKIN_STORAGE_TYPE}
      - MYSQL_DB=${ZIPKIN_MYSQL_DB}
      - MYSQL_USER=${ZIPKIN_MYSQL_USER}
      - MYSQL_PASS=${ZIPKIN_MYSQL_PASS}
      - MYSQL_HOST=${ZIPKIN_MYSQL_HOST}
      - MYSQL_TCP_PORT=${ZIPKIN_MYSQL_TCP_PORT}
      - ZIPKIN_VERSION=${ZIPKIN_VERSION}
      - TZ=${TIME_ZONE}

  ### Grafana ################################################
  grafana:
    build: ./grafana
    volumes:
     - ${VOLUMES_PATH}/grafana:/var/lib/grafana
    environment:
     - GRAFANA_VERSION=${VOLUMES_PATH}
    ports:
     - "${GRAFANA_PORT}:3000"

  ### prometheus ################################################
  prometheus:
    build:
      context: ./prometheus
    volumes:
      - ./prometheus:/etc/prometheus/
      - ${VOLUMES_PATH}/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "${PROMETHEUS_PORT}:9090"


