ARG PULSAR_MANAGER_VERSION
FROM apachepulsar/pulsar-manager:${PULSAR_MANAGER_VERSION}
LABEL maintainer="liuqinghui <liuqinghui1991@163.com>"

## 安装curl
#RUN apk add --no-cache curl
#
## 拷贝文件
#COPY admin_password.sh /home/
## 执行权限
#RUN chmod 777 /home/admin_password.sh
##CMD ["sh","/home/admin_password.sh"]
