ARG PHP_VERSION
FROM registry.cn-beijing.aliyuncs.com/liuqinghui/php-dev-env:workspace-${PHP_VERSION}
LABEL maintainer="liuqinghui <liuqinghui1991@163.com>"

ARG WORKSPACE_PORT_LIST
EXPOSE ${WORKSPACE_PORT_LIST}



